; Darkmatter LLVM-IR assembly file
;
; NOTE: This file was generated by the Darkmatter compiler.
; Any edits made may not reflect the original source code,
; and may lead to unpredictable results!
;
; Source File:            exit_42.dm
; Source Hash:            f25b46e59c7f38d786b8f95fa365ee6a94a18bb7
; Compiler:               Darkmatter
; Compiler Version:       0.1.0
;
!_DMC_SRC = !"exit_42.dm"
!_DMC_SRC_INT = !"f25b46e59c7f38d786b8f95fa365ee6a94a18bb7"
!_DMC_VENDOR = !"Darkmatter"
!_DMC_VER = !{!0, !1, !0}
!_DMC_DAT = !{u64 1701729210}
!_DMC_INT = !"285d57af84abebdcbee7a2ef45d35d54c4c2379b"
!_DMC_OPT = !{!0}
