; Darkmatter LLVM-IR assembly file
;
; NOTE: This file was generated by the Darkmatter compiler.
; Any edits made may not reflect the original source code,
; and may lead to unpredictable results!
;
; Source File:            tampered.dm
; Source Hash:            3ba512e0eddd801e73107ad0d73c2efa012d307b
; Compiler:               Darkmatter
; Compiler Version:       0.1.0
;
!_DMC_SRC = !"tampered.dm"
!_DMC_SRC_INT = !"3ba512e0eddd801e73107ad0d73c2efa012d307b"
!_DMC_VENDOR = !"Darkmatter"
!_DMC_VER = !{!0, !1, !0}
!_DMC_DAT = !{u64 1701729210}
!_DMC_INT = !"asdf"
!_DMC_OPT = !{!0}


